module.exports = {
   
    rules: {
        "no-const-assign": "error",
        "no-compare-neg-zero" : "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "error",
        "no-unused-vars": "error",
        "no-use-before-define": "error",
        "use-isnan": "error",
        "accessor-pairs": "error",
        "default-case": "error",
        "eqeqeq": ["error", "always"],
        "func-style": ["error", "expression"],
        "max-depth": ["error", 4],
        "no-bitwise": "error",
        "no-console": "error",
        "no-empty": "error",
        "no-empty-function": "error",
        "no-eq-null": "error",
        "no-extra-semi": "error",
        "no-implied-eval": "error",
        "no-inline-comments": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-mixed-operators": "error",
        "no-multi-assign": "error",
        "no-multi-str": "error",
        "no-nested-ternary": "error",
        "no-return-await": "error",
        "no-throw-literal": "error",
        "no-var": "error",
        "operator-assignment": ["error", "always"],
        "prefer-template": "error",
        "quote-props": ["error", "always"],
        "spaced-comment": ["error", "always"] ,
        "vars-on-top": "error",
        "array-bracket-newline": ["error", "never"],
        "array-bracket-spacing": ["error", "always"],
        "array-element-newline": ["error", "never"],
        "arrow-spacing": ["error", { "before": false, "after": true }],
        "block-spacing": "error",
        "brace-style": "error",
        "comma-dangle": ["error", "never"],
        "comma-spacing": ["error", { "before": true, "after": true }],
        "comma-style": ["error", "last"],
        "computed-property-spacing": ["error", "always"],
        "dot-location": ["error", "object"],
        "func-call-spacing": ["error", "always", { "allowNewlines": false }],
        "function-call-argument-newline": ["error", "never"],
        "generator-star-spacing": ["error", {"before": true, "after": true}],
        "implicit-arrow-linebreak": ["error", "beside"],
        "jsx-quotes": ["error", "prefer-single"],
        "key-spacing": ["error", { "beforeColon": true,"afterColon": true }],
        "line-comment-position": ["error", { "position": "above" }],
        "max-len": ["error", { "code": 70,"comments": 50,"ignoreUrls": true }],
        "max-statements-per-line": ["error", { "max": 1 }],
        "multiline-ternary": ["error", "never"],
        "no-multiple-empty-lines": ["error", { "max": 2}],
        "no-whitespace-before-property": "error",
        "object-curly-spacing": ["error", "always"],
        "operator-linebreak": ["error", "before"],
        "quotes": ["error", "single"],
        "semi": ["error", "always"],
        "semi-style": ["error", "last"],
        "semi-spacing": ["error", { "before": false, "after": false }],
        "space-infix-ops": ["error"]
        
    }
}